# Generated by Django 4.2.4 on 2023-10-12 05:31

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=20, prefix='CRED', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('number', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=16, max_length=16, prefix='', unique=True)),
                ('month', models.DateField(auto_now_add=True)),
                ('year', models.IntegerField()),
                ('cvv', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=3, max_length=3, prefix='', unique=True)),
                ('card_type', models.CharField(choices=[['master', 'MASTER'], ['visa', 'VISA'], ['rupay', 'RUPAY'], ['platinum', 'PLATINUM']], max_length=200)),
                ('card_status', models.CharField(choices=[['active', 'ACTIVE'], ['inactive', 'INACTIVE']], max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
