# Generated by Django 4.2.4 on 2023-10-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_creditcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='month',
            field=models.CharField(max_length=200),
        ),
    ]
