# Generated by Django 4.2.4 on 2023-10-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_creditcard_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
